version: '3.8'

services:
  app:
    build:
      context: .
    container_name: Product-Server
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: dbMongoDB
      MONGO_PORT: 27017


  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: 'mongo:latest'
    container_name: product-server-mongodb
    volumes:
      - db:/var/lib/mongodb
    ports:
      - "27017:27017"
volumes:
  db:
  mongodb: